# Generated by Django 5.0.4 on 2024-04-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clothapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
